version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.3
  - dependency-name: i18n
    versions:
    - 1.8.8
  - dependency-name: rspec-support
    versions:
    - 3.10.2
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: webpack
    versions:
    - 5.20.1
    - 5.34.0
    - 5.35.0
    - 5.36.0
  - dependency-name: css-loader
    versions:
    - 5.2.4
  - dependency-name: "@sentry/browser"
    versions:
    - 6.3.0
  - dependency-name: css-minimizer-webpack-plugin
    versions:
    - 2.0.0
  - dependency-name: "@webpack-cli/serve"
    versions:
    - 1.3.1
  - dependency-name: "@tailwindcss/jit"
    versions:
    - 0.1.12
  - dependency-name: "@tailwindcss/forms"
    versions:
    - 0.3.0
