name: Setup Ruby and Bun
description: Install Ruby (with bundler cache), Bun, and JavaScript packages

runs:
  using: composite
  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Install JavaScript packages
      shell: bash
      run: bun install --frozen-lockfile
