plugins:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-thread_safety

AllCops:
  TargetRubyVersion: 3.4
  Exclude:
    - app/javascript/**/*
    - bin/**/*
    - coverage/**/*
    - db/schema.rb
    - db/migrate/**/*
    - log/**/*
    - node_modules/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*
  EnabledByDefault: true

### Rails

Rails/FilePath:
  EnforcedStyle: arguments

Rails/ApplicationController:
  Enabled: false

Rails/SchemaComment:
  Enabled: false

Rails/DefaultScope:
  Enabled: false

Rails/EnvironmentVariableAccess:
  AllowReads: true

Rails/SkipsModelValidations:
  AllowedMethods:
    - insert_all!
    - upsert_all
    - touch

### Bundler

Bundler/OrderedGems:
  Enabled: false

Bundler/GemVersion:
  Enabled: false

### Layout

Layout/CommentIndentation:
  Exclude:
    - 'spec/spec_helper.rb'

Layout/ClassStructure:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Layout/RedundantLineBreak:
  Enabled: false

Layout/SingleLineBlockChain:
  Enabled: false

Layout/EmptyLineAfterMultilineCondition:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineAssignmentLayout:
  Enabled: false

Layout/LineContinuationLeadingSpace:
  Enabled: false

Layout/EmptyComment:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space

### Metrics

Metrics/AbcSize:
  Max: 35
  Exclude:
    - 'spec/system/**'

Metrics/MethodLength:
  Max: 50

Metrics/BlockLength:
  Max: 110

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 110

Metrics/ParameterLists:
  Max: 6

### Style

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/InlineComment:
  Enabled: false

Style/StringHashKeys:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/IpAddresses:
  Enabled: false

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/QuotedSymbols:
  EnforcedStyle: single_quotes

Style/FormatStringToken:
  Exclude:
    - config/routes.rb

Style/RequireOrder:
  Enabled: false

Style/MultilineMethodSignature:
  Enabled: false

Style/ReturnNilInPredicateMethodDefinition:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/Lambda:
  EnforcedStyle: line_count_dependent

Style/EmptyMethod:
  Enabled: false

# Lint

Lint/ConstantResolution:
  Enabled: false

Lint/NumberConversion:
  Enabled: false

# RSpec

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/AlignLeftLetBrace:
  Enabled: false

RSpec/AlignRightLetBrace:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

# Naming

Naming/VariableNumber:
  Enabled: false

# Capybara

Capybara/AmbiguousClick:
  Enabled: false
