exclude:
  - 'vendor/**/*.slim'

linters:
  LineLength:
    enabled: false

  RuboCop:
    enabled: true

    ignored_cops:
      - Layout/FirstHashElementIndentation
      - Layout/IndentationWidth
      - Layout/ArgumentAlignment
      - Layout/TrailingEmptyLines
      - Layout/FirstArrayElementIndentation
      - Layout/LineLength
      - Style/IdenticalConditionalBranches
      - Style/Next
      - Style/RedundantLineContinuation
      - Lint/Void
