exclude:
  - "vendor/**/*.slim"

linters:
  LineLength:
    enabled: false

  RuboCop:
    enabled: true

    ignored_cops:
      - Layout/FirstHashElementIndentation
      - Layout/IndentationWidth
      - Layout/ArgumentAlignment
      - Layout/TrailingEmptyLines
      - Layout/FirstArrayElementIndentation
      - Style/IdenticalConditionalBranches
      - Lint/Void
