name: Fehlerbericht
description: Fehler in SOLECTRUS melden
type: Bug

body:
  - type: textarea
    id: description
    attributes:
      label: Beschreibung
      placeholder: Bitte unbedingt nur EIN Thema pro Issue, keine Sammlung von Problemen und Vorschlägen! Bei Screenshots bitte erläutern, worin genau der Fehler besteht.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Welche Version von SOLECTRUS verwendest du?
      placeholder: z.B. v0.19.1
    validations:
      required: true

  - type: input
    id: machine
    attributes:
      label: Auf welchem Gerät läuft bei dir SOLECTRUS?
      placeholder: z.B. Raspberry Pi 4
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Auszug aus dem Logfile, sofern zum Verständnis sinnvoll (z.B. bei einem Fehler 500)
      description: Kann abgerufen werden mit `docker compose logs`, aber beschränke dich auf die relevanten Zeilen.
      render: text

  - type: textarea
    id: compose
    attributes:
      label: Deine vollständige `docker-compose.yml` oder `compose.yml`
      description: Kann wichtig sein, z.B. bei Konfigurationsproblemen
      render: yaml
      placeholder: |
        z.B.:

        services:
          dashboard:
            image: ghcr.io/solectrus/solectrus:latest
        ...

  - type: textarea
    id: environment
    attributes:
      label: Deine vollständige `.env`
      description: Kann wichtig sein, z.B. bei Konfigurationsproblemen. Aus Datenschutzgründen bitte alle sensiblen Informationen unkenntlich machen (Passwörter, API-Schlüssel, Geodaten, etc.)
      render: text
      placeholder: |
        z.B:

        # Domain name or IP address of your host
        APP_HOST=raspberrypi

        # Date of commissioning of your photovoltaic system
        INSTALLATION_DATE=2023-04-03
        ...
