name: Anforderungsbeschreibung
description: Neues Feature für SOLECTRUS vorschlagen
type: Feature

body:
  - type: textarea
    id: description
    attributes:
      label: Beschreibung (auf Deutsch oder Englisch)
    validations:
      required: true
