name: Installationsproblem
description: Problem beim Installieren oder Konfigurieren von SOLECTRUS klären
type: Task
labels: ['help wanted']

body:
  - type: textarea
    id: description
    attributes:
      label: Beschreibung (auf Deutsch oder Englisch)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Welche Version von SOLECTRUS verwendest du?
      placeholder: z.B. v0.18.3
    validations:
      required: true

  - type: input
    id: machine
    attributes:
      label: Auf welchem Gerät läuft bei dir SOLECTRUS?
      placeholder: z.B. Raspberry Pi 4
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Auszug aus dem Logfile, sofern zum Verständnis sinnvoll (z.B. bei einem Fehler 500)
      description: Kann abgerufen werden mit `docker compose logs`, aber beschränke dich auf die relevanten Zeilen.
      render: text

  - type: textarea
    id: compose
    attributes:
      label: Dein vollständiges `docker-compose.yml` oder `compose.yml`
      render: yaml
      placeholder: |
        z.B.:

        services:
          dashboard:
            image: ghcr.io/solectrus/solectrus:latest
        ...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Dein vollständiges `.env`
      description: Aus Datenschutzgründen bitte alle sensiblen Informationen unkenntlich machen (Passwörter, API-Schlüssel, Geodaten, etc.)
      render: text
      placeholder: |
        z.B:

        # Domain name or IP address of your host
        APP_HOST=raspberrypi

        # Date of commissioning of your photovoltaic system
        INSTALLATION_DATE=2023-04-03
        ...
    validations:
      required: true
