blank_issues_enabled: false
contact_links:
  - name: Forum
    url: https://github.com/orgs/solectrus/discussions
    about: Für Fragen und alles zum Besprechen – auch bei Problemen mit Installation und Konfiguration
