# Turns the icon list in config/icons.yml into config/icons.generated.yml, the
# path data the app renders its icons from. Driven by `bin/rails icons:generate`.
#
# The icons used to be drawn in the browser: the markup carried
# `<i class="fa fa-gear">` and the Font Awesome runtime swapped each one for an
# SVG. That cost main thread time on every page and every Turbo navigation, and
# it moved the layout after the icons appeared. The server writes the same SVG
# now, and the runtime is gone from the bundle.
#
# The @fortawesome packages stay in package.json as a development dependency.
# They are the source this reads, and nothing ships them to the browser.
class IconGenerator
  PACKAGES = {
    'solid' => 'free-solid-svg-icons',
    'regular' => 'free-regular-svg-icons',
    'brands' => 'free-brands-svg-icons',
  }.freeze
  public_constant :PACKAGES

  PREFIXES = { 'solid' => 'fas', 'regular' => 'far', 'brands' => 'fab' }.freeze
  public_constant :PREFIXES

  class Error < StandardError
  end

  def initialize(
    list: Rails.root.join('config', 'icons.yml'),
    target: Rails.root.join('config', 'icons.generated.yml'),
    packages: Rails.root.join('node_modules', '@fortawesome')
  )
    @list = list
    @target = target
    @packages = packages
  end

  attr_reader :list, :target, :packages

  # Returns the number of icons written.
  def call
    icons = build

    File.open(target, 'w') do |file|
      file.puts '# Generated by `bin/rails icons:generate`. Do not edit.'
      file.puts '# Add or remove an icon in config/icons.yml, then run the task.'
      file.puts '#'
      attribution.each_line { |line| file.puts "# #{line.chomp}".rstrip }
      # line_width: -1 keeps every path on one line. A wrapped path still draws
      # the same shape, but it stops the file from diffing cleanly.
      file.write(icons.sort.to_h.to_yaml(line_width: -1))
    end

    icons.size
  end

  # CC BY 4.0 asks that the author, the copyright, the license and any changes
  # are named wherever the work travels. The path data below IS the work, so the
  # notice belongs in the same file, and it names the version it was taken from.
  def attribution
    <<~TEXT
      The path data below is taken from Font Awesome Free #{version}, unchanged.
      Only its container changed, from JavaScript modules to this file.

      Font Awesome Free by Fonticons, Inc. - https://fontawesome.com
      Icons licensed under CC BY 4.0 - https://creativecommons.org/licenses/by/4.0/
      Full license: https://fontawesome.com/license/free
    TEXT
  end

  def version
    JSON.parse(File.read(packages.join('free-solid-svg-icons', 'package.json')))[
      'version',
    ]
  end

  private

  def build
    YAML
      .load_file(list)
      .flat_map { |style, names| Array(names).map { |name| [style, name] } }
      .to_h { |style, name| [name, icon(style, name)] }
  end

  def icon(style, name)
    source = read(style, name)

    {
      'prefix' => PREFIXES[style],
      'width' => capture(source, /var width = (\d+);/, name).to_i,
      'height' => capture(source, /var height = (\d+);/, name).to_i,
      'path' => capture(source, /var svgPathData = '([^']+)';/, name),
    }
  end

  # The package files are CommonJS and follow a fixed shape, so a few patterns
  # are enough and save pulling in a JavaScript runtime here.
  def read(style, name)
    file = file_for(style, variable_for(name))

    unless File.exist?(file)
      raise Error,
            "config/icons.yml lists #{name} as #{style}, but #{file} does not exist. Check the name and the style."
    end

    source = File.read(file)

    # An alias holds no data and delegates with `var source = require('./faHouse')`.
    # Follow it to name the canonical icon, so the list says what it renders.
    if (target = source[%r{require\('\./(fa\w+)'\)}, 1])
      canonical =
        File.read(file_for(style, target))[/var iconName = '([\w-]+)';/, 1]
      raise Error,
            "config/icons.yml lists #{name}, which is an alias. Use #{canonical} instead."
    end

    source
  end

  def file_for(style, variable)
    packages.join(PACKAGES[style].to_s, "#{variable}.js")
  end

  def variable_for(name)
    "fa#{name.split('-').map(&:capitalize).join}"
  end

  def capture(source, pattern, name)
    source[pattern, 1] ||
      raise(
        Error,
        "Cannot read #{name} from its package file: #{pattern.source} found nothing.",
      )
  end
end
