---
http_interactions:
- request:
    method: post
    uri: https://<INFLUX_HOST>/api/v2/query?org=<INFLUX_ORG>
    body:
      encoding: UTF-8
      string: '{"query":"      from(bucket: \"<INFLUX_BUCKET>\")\n      |\u003e range(start:
        -1h)\n      |\u003e filter(fn: (r) =\u003e r[\"_measurement\"] == \"<INFLUX_BUCKET>\")\n      |\u003e
        filter(fn: (r) =\u003e r[\"_field\"] == \"inverter_power\" or r[\"_field\"]
        == \"house_power\" or r[\"_field\"] == \"grid_power_plus\" or r[\"_field\"]
        == \"grid_power_minus\" or r[\"_field\"] == \"bat_power_minus\" or r[\"_field\"]
        == \"bat_power_plus\" or r[\"_field\"] == \"bat_fuel_charge\")\n      |\u003e
        last()\n","dialect":{"header":true,"delimiter":",","annotations":["datatype","group","default"],"commentPrefix":"#","dateTimeFormat":"RFC3339"}}'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - influxdb-client-ruby/1.10.0
      Authorization:
      - Token <INFLUX_TOKEN>
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - text/csv; charset=utf-8
      Date:
      - Sat, 02 Jan 2021 18:18:21 GMT
      Vary:
      - Accept-Encoding
      Content-Length:
      - '1252'
    body:
      encoding: UTF-8
      string: "#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string\r\n#group,false,false,true,true,false,false,true,true\r\n#default,_result,,,,,,,\r\n,result,table,_start,_stop,_time,_value,_field,_measurement\r\n,,0,2021-01-02T17:18:21.309031361Z,2021-01-02T18:18:21.309031361Z,2021-01-02T18:18:17Z,0,bat_fuel_charge,<INFLUX_BUCKET>\r\n\r\n#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,long,string,string\r\n#group,false,false,true,true,false,false,true,true\r\n#default,_result,,,,,,,\r\n,result,table,_start,_stop,_time,_value,_field,_measurement\r\n,,1,2021-01-02T17:18:21.309031361Z,2021-01-02T18:18:21.309031361Z,2021-01-02T18:18:17Z,10,bat_power_minus,<INFLUX_BUCKET>\r\n,,2,2021-01-02T17:18:21.309031361Z,2021-01-02T18:18:21.309031361Z,2021-01-02T18:18:17Z,0,bat_power_plus,<INFLUX_BUCKET>\r\n,,3,2021-01-02T17:18:21.309031361Z,2021-01-02T18:18:21.309031361Z,2021-01-02T18:18:17Z,0,grid_power_minus,<INFLUX_BUCKET>\r\n,,4,2021-01-02T17:18:21.309031361Z,2021-01-02T18:18:21.309031361Z,2021-01-02T18:18:17Z,441,grid_power_plus,<INFLUX_BUCKET>\r\n,,5,2021-01-02T17:18:21.309031361Z,2021-01-02T18:18:21.309031361Z,2021-01-02T18:18:17Z,451,house_power,<INFLUX_BUCKET>\r\n,,6,2021-01-02T17:18:21.309031361Z,2021-01-02T18:18:21.309031361Z,2021-01-02T18:18:17Z,0,inverter_power,<INFLUX_BUCKET>\r\n\r\n"
  recorded_at: Sat, 02 Jan 2021 18:18:21 GMT
- request:
    method: post
    uri: https://<INFLUX_HOST>/api/v2/query?org=<INFLUX_ORG>
    body:
      encoding: UTF-8
      string: '{"query":"      from(bucket: \"<INFLUX_BUCKET>\")\n      |\u003e range(start:
        -1h)\n      |\u003e filter(fn: (r) =\u003e r[\"_measurement\"] == \"<INFLUX_BUCKET>\")\n      |\u003e
        filter(fn: (r) =\u003e r[\"_field\"] == \"inverter_power\" or r[\"_field\"]
        == \"house_power\" or r[\"_field\"] == \"grid_power_plus\" or r[\"_field\"]
        == \"grid_power_minus\" or r[\"_field\"] == \"bat_power_minus\" or r[\"_field\"]
        == \"bat_power_plus\" or r[\"_field\"] == \"bat_fuel_charge\")\n      |\u003e
        last()\n","dialect":{"header":true,"delimiter":",","annotations":["datatype","group","default"],"commentPrefix":"#","dateTimeFormat":"RFC3339"}}'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - influxdb-client-ruby/1.10.0
      Authorization:
      - Token <INFLUX_TOKEN>
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - text/csv; charset=utf-8
      Date:
      - Sat, 02 Jan 2021 18:18:21 GMT
      Vary:
      - Accept-Encoding
      Content-Length:
      - '1252'
    body:
      encoding: UTF-8
      string: "#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string\r\n#group,false,false,true,true,false,false,true,true\r\n#default,_result,,,,,,,\r\n,result,table,_start,_stop,_time,_value,_field,_measurement\r\n,,0,2021-01-02T17:18:21.522836154Z,2021-01-02T18:18:21.522836154Z,2021-01-02T18:18:17Z,0,bat_fuel_charge,<INFLUX_BUCKET>\r\n\r\n#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,long,string,string\r\n#group,false,false,true,true,false,false,true,true\r\n#default,_result,,,,,,,\r\n,result,table,_start,_stop,_time,_value,_field,_measurement\r\n,,1,2021-01-02T17:18:21.522836154Z,2021-01-02T18:18:21.522836154Z,2021-01-02T18:18:17Z,10,bat_power_minus,<INFLUX_BUCKET>\r\n,,2,2021-01-02T17:18:21.522836154Z,2021-01-02T18:18:21.522836154Z,2021-01-02T18:18:17Z,0,bat_power_plus,<INFLUX_BUCKET>\r\n,,3,2021-01-02T17:18:21.522836154Z,2021-01-02T18:18:21.522836154Z,2021-01-02T18:18:17Z,0,grid_power_minus,<INFLUX_BUCKET>\r\n,,4,2021-01-02T17:18:21.522836154Z,2021-01-02T18:18:21.522836154Z,2021-01-02T18:18:17Z,441,grid_power_plus,<INFLUX_BUCKET>\r\n,,5,2021-01-02T17:18:21.522836154Z,2021-01-02T18:18:21.522836154Z,2021-01-02T18:18:17Z,451,house_power,<INFLUX_BUCKET>\r\n,,6,2021-01-02T17:18:21.522836154Z,2021-01-02T18:18:21.522836154Z,2021-01-02T18:18:17Z,0,inverter_power,<INFLUX_BUCKET>\r\n\r\n"
  recorded_at: Sat, 02 Jan 2021 18:18:21 GMT
- request:
    method: post
    uri: https://<INFLUX_HOST>/api/v2/query?org=<INFLUX_ORG>
    body:
      encoding: UTF-8
      string: '{"query":"      from(bucket: \"<INFLUX_BUCKET>\")\n      |\u003e range(start:
        -24h)\n      |\u003e filter(fn: (r) =\u003e r[\"_measurement\"] == \"<INFLUX_BUCKET>\")\n      |\u003e
        filter(fn: (r) =\u003e r[\"_field\"] == \"inverter_power\" or r[\"_field\"]
        == \"house_power\" or r[\"_field\"] == \"grid_power_plus\" or r[\"_field\"]
        == \"grid_power_minus\" or r[\"_field\"] == \"bat_power_minus\" or r[\"_field\"]
        == \"bat_power_plus\")\n      |\u003e aggregateWindow(every: 1h, fn: mean)\n      |\u003e
        sum()\n","dialect":{"header":true,"delimiter":",","annotations":["datatype","group","default"],"commentPrefix":"#","dateTimeFormat":"RFC3339"}}'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - influxdb-client-ruby/1.10.0
      Authorization:
      - Token <INFLUX_TOKEN>
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - text/csv; charset=utf-8
      Date:
      - Sat, 02 Jan 2021 18:18:22 GMT
      Vary:
      - Accept-Encoding
      Content-Length:
      - '829'
    body:
      encoding: UTF-8
      string: "#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,string,string,double\r\n#group,false,false,true,true,true,true,false\r\n#default,_result,,,,,,\r\n,result,table,_start,_stop,_field,_measurement,_value\r\n,,0,2021-01-01T18:18:22.469955624Z,2021-01-02T18:18:22.469955624Z,bat_power_minus,<INFLUX_BUCKET>,61.769591454789996\r\n,,1,2021-01-01T18:18:22.469955624Z,2021-01-02T18:18:22.469955624Z,bat_power_plus,<INFLUX_BUCKET>,0\r\n,,2,2021-01-01T18:18:22.469955624Z,2021-01-02T18:18:22.469955624Z,grid_power_minus,<INFLUX_BUCKET>,3.1787581699346408\r\n,,3,2021-01-01T18:18:22.469955624Z,2021-01-02T18:18:22.469955624Z,grid_power_plus,<INFLUX_BUCKET>,1989.6710089160422\r\n,,4,2021-01-01T18:18:22.469955624Z,2021-01-02T18:18:22.469955624Z,house_power,<INFLUX_BUCKET>,2561.879116352453\r\n,,5,2021-01-01T18:18:22.469955624Z,2021-01-02T18:18:22.469955624Z,inverter_power,<INFLUX_BUCKET>,513.1553989647057\r\n\r\n"
  recorded_at: Sat, 02 Jan 2021 18:18:22 GMT
- request:
    method: post
    uri: https://<INFLUX_HOST>/api/v2/query?org=<INFLUX_ORG>
    body:
      encoding: UTF-8
      string: '{"query":"      from(bucket: \"<INFLUX_BUCKET>\")\n      |\u003e range(start:
        -7d)\n      |\u003e filter(fn: (r) =\u003e r[\"_measurement\"] == \"<INFLUX_BUCKET>\")\n      |\u003e
        filter(fn: (r) =\u003e r[\"_field\"] == \"inverter_power\" or r[\"_field\"]
        == \"house_power\" or r[\"_field\"] == \"grid_power_plus\" or r[\"_field\"]
        == \"grid_power_minus\" or r[\"_field\"] == \"bat_power_minus\" or r[\"_field\"]
        == \"bat_power_plus\")\n      |\u003e aggregateWindow(every: 1h, fn: mean)\n      |\u003e
        sum()\n","dialect":{"header":true,"delimiter":",","annotations":["datatype","group","default"],"commentPrefix":"#","dateTimeFormat":"RFC3339"}}'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - influxdb-client-ruby/1.10.0
      Authorization:
      - Token <INFLUX_TOKEN>
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - text/csv; charset=utf-8
      Date:
      - Sat, 02 Jan 2021 18:18:23 GMT
      Vary:
      - Accept-Encoding
      Content-Length:
      - '843'
    body:
      encoding: UTF-8
      string: "#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,string,string,double\r\n#group,false,false,true,true,true,true,false\r\n#default,_result,,,,,,\r\n,result,table,_start,_stop,_field,_measurement,_value\r\n,,0,2020-12-26T18:18:23.249219687Z,2021-01-02T18:18:23.249219687Z,bat_power_minus,<INFLUX_BUCKET>,5062.609356580967\r\n,,1,2020-12-26T18:18:23.249219687Z,2021-01-02T18:18:23.249219687Z,bat_power_plus,<INFLUX_BUCKET>,27.84090909090909\r\n,,2,2020-12-26T18:18:23.249219687Z,2021-01-02T18:18:23.249219687Z,grid_power_minus,<INFLUX_BUCKET>,243.0537581699346\r\n,,3,2020-12-26T18:18:23.249219687Z,2021-01-02T18:18:23.249219687Z,grid_power_plus,<INFLUX_BUCKET>,9379.022460302822\r\n,,4,2020-12-26T18:18:23.249219687Z,2021-01-02T18:18:23.249219687Z,house_power,<INFLUX_BUCKET>,16440.60447529303\r\n,,5,2020-12-26T18:18:23.249219687Z,2021-01-02T18:18:23.249219687Z,inverter_power,<INFLUX_BUCKET>,2272.3094347236324\r\n\r\n"
  recorded_at: Sat, 02 Jan 2021 18:18:23 GMT
- request:
    method: post
    uri: https://<INFLUX_HOST>/api/v2/query?org=<INFLUX_ORG>
    body:
      encoding: UTF-8
      string: '{"query":"      from(bucket: \"<INFLUX_BUCKET>\")\n      |\u003e range(start:
        -30d)\n      |\u003e filter(fn: (r) =\u003e r[\"_measurement\"] == \"<INFLUX_BUCKET>\")\n      |\u003e
        filter(fn: (r) =\u003e r[\"_field\"] == \"inverter_power\" or r[\"_field\"]
        == \"house_power\" or r[\"_field\"] == \"grid_power_plus\" or r[\"_field\"]
        == \"grid_power_minus\" or r[\"_field\"] == \"bat_power_minus\" or r[\"_field\"]
        == \"bat_power_plus\")\n      |\u003e aggregateWindow(every: 1h, fn: mean)\n      |\u003e
        sum()\n","dialect":{"header":true,"delimiter":",","annotations":["datatype","group","default"],"commentPrefix":"#","dateTimeFormat":"RFC3339"}}'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - influxdb-client-ruby/1.10.0
      Authorization:
      - Token <INFLUX_TOKEN>
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - text/csv; charset=utf-8
      Date:
      - Sat, 02 Jan 2021 18:18:23 GMT
      Vary:
      - Accept-Encoding
      Content-Length:
      - '843'
    body:
      encoding: UTF-8
      string: "#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,string,string,double\r\n#group,false,false,true,true,true,true,false\r\n#default,_result,,,,,,\r\n,result,table,_start,_stop,_field,_measurement,_value\r\n,,0,2020-12-03T18:18:23.396022336Z,2021-01-02T18:18:23.396022336Z,bat_power_minus,<INFLUX_BUCKET>,80850.25620972786\r\n,,1,2020-12-03T18:18:23.396022336Z,2021-01-02T18:18:23.396022336Z,bat_power_plus,<INFLUX_BUCKET>,81058.11701631699\r\n,,2,2020-12-03T18:18:23.396022336Z,2021-01-02T18:18:23.396022336Z,grid_power_minus,<INFLUX_BUCKET>,31440.98248777366\r\n,,3,2020-12-03T18:18:23.396022336Z,2021-01-02T18:18:23.396022336Z,grid_power_plus,<INFLUX_BUCKET>,204150.4535209089\r\n,,4,2020-12-03T18:18:23.396022336Z,2021-01-02T18:18:23.396022336Z,house_power,<INFLUX_BUCKET>,296095.8877503512\r\n,,5,2020-12-03T18:18:23.396022336Z,2021-01-02T18:18:23.396022336Z,inverter_power,<INFLUX_BUCKET>,220847.62039043463\r\n\r\n"
  recorded_at: Sat, 02 Jan 2021 18:18:23 GMT
- request:
    method: post
    uri: https://<INFLUX_HOST>/api/v2/query?org=<INFLUX_ORG>
    body:
      encoding: UTF-8
      string: '{"query":"      from(bucket: \"<INFLUX_BUCKET>\")\n      |\u003e range(start:
        -365d)\n      |\u003e filter(fn: (r) =\u003e r[\"_measurement\"] == \"<INFLUX_BUCKET>\")\n      |\u003e
        filter(fn: (r) =\u003e r[\"_field\"] == \"inverter_power\" or r[\"_field\"]
        == \"house_power\" or r[\"_field\"] == \"grid_power_plus\" or r[\"_field\"]
        == \"grid_power_minus\" or r[\"_field\"] == \"bat_power_minus\" or r[\"_field\"]
        == \"bat_power_plus\")\n      |\u003e aggregateWindow(every: 1h, fn: mean)\n      |\u003e
        sum()\n","dialect":{"header":true,"delimiter":",","annotations":["datatype","group","default"],"commentPrefix":"#","dateTimeFormat":"RFC3339"}}'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - influxdb-client-ruby/1.10.0
      Authorization:
      - Token <INFLUX_TOKEN>
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - text/csv; charset=utf-8
      Date:
      - Sat, 02 Jan 2021 18:18:24 GMT
      Vary:
      - Accept-Encoding
      Content-Length:
      - '847'
    body:
      encoding: UTF-8
      string: "#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,string,string,double\r\n#group,false,false,true,true,true,true,false\r\n#default,_result,,,,,,\r\n,result,table,_start,_stop,_field,_measurement,_value\r\n,,0,2020-01-03T18:18:24.242531027Z,2021-01-02T18:18:24.242531027Z,bat_power_minus,<INFLUX_BUCKET>,105927.23348245512\r\n,,1,2020-01-03T18:18:24.242531027Z,2021-01-02T18:18:24.242531027Z,bat_power_plus,<INFLUX_BUCKET>,104133.31398601396\r\n,,2,2020-01-03T18:18:24.242531027Z,2021-01-02T18:18:24.242531027Z,grid_power_minus,<INFLUX_BUCKET>,43160.012790803965\r\n,,3,2020-01-03T18:18:24.242531027Z,2021-01-02T18:18:24.242531027Z,grid_power_plus,<INFLUX_BUCKET>,232624.46867242403\r\n,,4,2020-01-03T18:18:24.242531027Z,2021-01-02T18:18:24.242531027Z,house_power,<INFLUX_BUCKET>,371028.08850792714\r\n,,5,2020-01-03T18:18:24.242531027Z,2021-01-02T18:18:24.242531027Z,inverter_power,<INFLUX_BUCKET>,277005.3703904345\r\n\r\n"
  recorded_at: Sat, 02 Jan 2021 18:18:24 GMT
- request:
    method: post
    uri: https://<INFLUX_HOST>/api/v2/query?org=<INFLUX_ORG>
    body:
      encoding: UTF-8
      string: '{"query":"      from(bucket: \"<INFLUX_BUCKET>\")\n      |\u003e range(start:
        0)\n      |\u003e filter(fn: (r) =\u003e r[\"_measurement\"] == \"<INFLUX_BUCKET>\")\n      |\u003e
        filter(fn: (r) =\u003e r[\"_field\"] == \"inverter_power\" or r[\"_field\"]
        == \"house_power\" or r[\"_field\"] == \"grid_power_plus\" or r[\"_field\"]
        == \"grid_power_minus\" or r[\"_field\"] == \"bat_power_minus\" or r[\"_field\"]
        == \"bat_power_plus\")\n      |\u003e aggregateWindow(every: 1h, fn: mean)\n      |\u003e
        sum()\n","dialect":{"header":true,"delimiter":",","annotations":["datatype","group","default"],"commentPrefix":"#","dateTimeFormat":"RFC3339"}}'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - influxdb-client-ruby/1.10.0
      Authorization:
      - Token <INFLUX_TOKEN>
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - text/csv; charset=utf-8
      Date:
      - Sat, 02 Jan 2021 18:18:24 GMT
      Vary:
      - Accept-Encoding
      Content-Length:
      - '781'
    body:
      encoding: UTF-8
      string: "#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,string,string,double\r\n#group,false,false,true,true,true,true,false\r\n#default,_result,,,,,,\r\n,result,table,_start,_stop,_field,_measurement,_value\r\n,,0,1970-01-01T00:00:00Z,2021-01-02T18:18:24.35456073Z,bat_power_minus,<INFLUX_BUCKET>,105927.23348245512\r\n,,1,1970-01-01T00:00:00Z,2021-01-02T18:18:24.35456073Z,bat_power_plus,<INFLUX_BUCKET>,104133.31398601396\r\n,,2,1970-01-01T00:00:00Z,2021-01-02T18:18:24.35456073Z,grid_power_minus,<INFLUX_BUCKET>,43160.012790803965\r\n,,3,1970-01-01T00:00:00Z,2021-01-02T18:18:24.35456073Z,grid_power_plus,<INFLUX_BUCKET>,232624.46867242403\r\n,,4,1970-01-01T00:00:00Z,2021-01-02T18:18:24.35456073Z,house_power,<INFLUX_BUCKET>,371028.08850792714\r\n,,5,1970-01-01T00:00:00Z,2021-01-02T18:18:24.35456073Z,inverter_power,<INFLUX_BUCKET>,277005.3703904345\r\n\r\n"
  recorded_at: Sat, 02 Jan 2021 18:18:24 GMT
recorded_with: VCR 6.0.0
