---
http_interactions:
- request:
    method: post
    uri: https://<INFLUX_HOST>/api/v2/query?org=<INFLUX_ORG>
    body:
      encoding: UTF-8
      string: '{"query":"      from(bucket: \"<INFLUX_BUCKET>\")\n      |\u003e range(start:
        -5d)\n      |\u003e filter(fn: (r) =\u003e r[\"_measurement\"] == \"<INFLUX_BUCKET>\")\n      |\u003e
        filter(fn: (r) =\u003e r[\"_field\"] == \"inverter_power\" or r[\"_field\"]
        == \"house_power\" or r[\"_field\"] == \"grid_power_plus\" or r[\"_field\"]
        == \"grid_power_minus\" or r[\"_field\"] == \"bat_fuel_charge\" or r[\"_field\"]
        == \"bat_power_minus\" or r[\"_field\"] == \"bat_power_plus\")\n      |\u003e
        last()\n","dialect":{"header":true,"delimiter":",","annotations":["datatype","group","default"],"commentPrefix":"#","dateTimeFormat":"RFC3339"}}'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - influxdb-client-ruby/1.10.0
      Authorization:
      - Token <INFLUX_TOKEN>
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - text/csv; charset=utf-8
      Date:
      - Sat, 02 Jan 2021 09:00:47 GMT
      Vary:
      - Accept-Encoding
      Content-Length:
      - '1253'
    body:
      encoding: UTF-8
      string: "#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string\r\n#group,false,false,true,true,false,false,true,true\r\n#default,_result,,,,,,,\r\n,result,table,_start,_stop,_time,_value,_field,_measurement\r\n,,0,2020-12-28T09:00:47.938008544Z,2021-01-02T09:00:47.938008544Z,2021-01-02T09:00:43Z,0,bat_fuel_charge,<INFLUX_BUCKET>\r\n\r\n#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,long,string,string\r\n#group,false,false,true,true,false,false,true,true\r\n#default,_result,,,,,,,\r\n,result,table,_start,_stop,_time,_value,_field,_measurement\r\n,,1,2020-12-28T09:00:47.938008544Z,2021-01-02T09:00:47.938008544Z,2021-01-02T09:00:43Z,7,bat_power_minus,<INFLUX_BUCKET>\r\n,,2,2020-12-28T09:00:47.938008544Z,2021-01-02T09:00:47.938008544Z,2021-01-02T09:00:43Z,0,bat_power_plus,<INFLUX_BUCKET>\r\n,,3,2020-12-28T09:00:47.938008544Z,2021-01-02T09:00:47.938008544Z,2021-01-02T09:00:43Z,0,grid_power_minus,<INFLUX_BUCKET>\r\n,,4,2020-12-28T09:00:47.938008544Z,2021-01-02T09:00:47.938008544Z,2021-01-02T09:00:43Z,117,grid_power_plus,<INFLUX_BUCKET>\r\n,,5,2020-12-28T09:00:47.938008544Z,2021-01-02T09:00:47.938008544Z,2021-01-02T09:00:43Z,350,house_power,<INFLUX_BUCKET>\r\n,,6,2020-12-28T09:00:47.938008544Z,2021-01-02T09:00:47.938008544Z,2021-01-02T09:00:43Z,227,inverter_power,<INFLUX_BUCKET>\r\n\r\n"
  recorded_at: Sat, 02 Jan 2021 09:00:47 GMT
- request:
    method: post
    uri: https://<INFLUX_HOST>/api/v2/query?org=<INFLUX_ORG>
    body:
      encoding: UTF-8
      string: '{"query":"      from(bucket: \"<INFLUX_BUCKET>\")\n      |\u003e range(start:
        -5d)\n      |\u003e filter(fn: (r) =\u003e r[\"_measurement\"] == \"<INFLUX_BUCKET>\")\n      |\u003e
        filter(fn: (r) =\u003e r[\"_field\"] == \"inverter_power\" or r[\"_field\"]
        == \"house_power\" or r[\"_field\"] == \"grid_power_plus\" or r[\"_field\"]
        == \"grid_power_minus\" or r[\"_field\"] == \"bat_fuel_charge\" or r[\"_field\"]
        == \"bat_power_minus\" or r[\"_field\"] == \"bat_power_plus\")\n      |\u003e
        last()\n","dialect":{"header":true,"delimiter":",","annotations":["datatype","group","default"],"commentPrefix":"#","dateTimeFormat":"RFC3339"}}'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - influxdb-client-ruby/1.10.0
      Authorization:
      - Token <INFLUX_TOKEN>
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - text/csv; charset=utf-8
      Date:
      - Sat, 02 Jan 2021 09:00:48 GMT
      Vary:
      - Accept-Encoding
      Content-Length:
      - '1239'
    body:
      encoding: UTF-8
      string: "#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string\r\n#group,false,false,true,true,false,false,true,true\r\n#default,_result,,,,,,,\r\n,result,table,_start,_stop,_time,_value,_field,_measurement\r\n,,0,2020-12-28T09:00:48.13339336Z,2021-01-02T09:00:48.13339336Z,2021-01-02T09:00:43Z,0,bat_fuel_charge,<INFLUX_BUCKET>\r\n\r\n#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,long,string,string\r\n#group,false,false,true,true,false,false,true,true\r\n#default,_result,,,,,,,\r\n,result,table,_start,_stop,_time,_value,_field,_measurement\r\n,,1,2020-12-28T09:00:48.13339336Z,2021-01-02T09:00:48.13339336Z,2021-01-02T09:00:43Z,7,bat_power_minus,<INFLUX_BUCKET>\r\n,,2,2020-12-28T09:00:48.13339336Z,2021-01-02T09:00:48.13339336Z,2021-01-02T09:00:43Z,0,bat_power_plus,<INFLUX_BUCKET>\r\n,,3,2020-12-28T09:00:48.13339336Z,2021-01-02T09:00:48.13339336Z,2021-01-02T09:00:43Z,0,grid_power_minus,<INFLUX_BUCKET>\r\n,,4,2020-12-28T09:00:48.13339336Z,2021-01-02T09:00:48.13339336Z,2021-01-02T09:00:43Z,117,grid_power_plus,<INFLUX_BUCKET>\r\n,,5,2020-12-28T09:00:48.13339336Z,2021-01-02T09:00:48.13339336Z,2021-01-02T09:00:43Z,350,house_power,<INFLUX_BUCKET>\r\n,,6,2020-12-28T09:00:48.13339336Z,2021-01-02T09:00:48.13339336Z,2021-01-02T09:00:43Z,227,inverter_power,<INFLUX_BUCKET>\r\n\r\n"
  recorded_at: Sat, 02 Jan 2021 09:00:48 GMT
- request:
    method: post
    uri: https://<INFLUX_HOST>/api/v2/query?org=<INFLUX_ORG>
    body:
      encoding: UTF-8
      string: '{"query":"      from(bucket: \"<INFLUX_BUCKET>\")\n      |\u003e range(start:
        -24h)\n      |\u003e filter(fn: (r) =\u003e r[\"_measurement\"] == \"<INFLUX_BUCKET>\")\n      |\u003e
        filter(fn: (r) =\u003e r[\"_field\"] == \"inverter_power\" or r[\"_field\"]
        == \"house_power\" or r[\"_field\"] == \"grid_power_plus\" or r[\"_field\"]
        == \"grid_power_minus\" or r[\"_field\"] == \"bat_fuel_charge\" or r[\"_field\"]
        == \"bat_power_minus\" or r[\"_field\"] == \"bat_power_plus\")\n      |\u003e
        aggregateWindow(every: 1h, fn: mean)\n      |\u003e sum()\n","dialect":{"header":true,"delimiter":",","annotations":["datatype","group","default"],"commentPrefix":"#","dateTimeFormat":"RFC3339"}}'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - influxdb-client-ruby/1.10.0
      Authorization:
      - Token <INFLUX_TOKEN>
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - text/csv; charset=utf-8
      Date:
      - Sat, 02 Jan 2021 09:00:49 GMT
      Vary:
      - Accept-Encoding
      Content-Length:
      - '905'
    body:
      encoding: UTF-8
      string: "#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,string,string,double\r\n#group,false,false,true,true,true,true,false\r\n#default,_result,,,,,,\r\n,result,table,_start,_stop,_field,_measurement,_value\r\n,,0,2021-01-01T09:00:49.146096195Z,2021-01-02T09:00:49.146096195Z,bat_fuel_charge,<INFLUX_BUCKET>,0\r\n,,1,2021-01-01T09:00:49.146096195Z,2021-01-02T09:00:49.146096195Z,bat_power_minus,<INFLUX_BUCKET>,28.729021662626103\r\n,,2,2021-01-01T09:00:49.146096195Z,2021-01-02T09:00:49.146096195Z,bat_power_plus,<INFLUX_BUCKET>,0\r\n,,3,2021-01-01T09:00:49.146096195Z,2021-01-02T09:00:49.146096195Z,grid_power_minus,<INFLUX_BUCKET>,0\r\n,,4,2021-01-01T09:00:49.146096195Z,2021-01-02T09:00:49.146096195Z,grid_power_plus,<INFLUX_BUCKET>,1409.7025284993995\r\n,,5,2021-01-01T09:00:49.146096195Z,2021-01-02T09:00:49.146096195Z,house_power,<INFLUX_BUCKET>,1776.4633175387564\r\n,,6,2021-01-01T09:00:49.146096195Z,2021-01-02T09:00:49.146096195Z,inverter_power,<INFLUX_BUCKET>,339.41444175922766\r\n\r\n"
  recorded_at: Sat, 02 Jan 2021 09:00:49 GMT
- request:
    method: post
    uri: https://<INFLUX_HOST>/api/v2/query?org=<INFLUX_ORG>
    body:
      encoding: UTF-8
      string: '{"query":"      from(bucket: \"<INFLUX_BUCKET>\")\n      |\u003e range(start:
        -7d)\n      |\u003e filter(fn: (r) =\u003e r[\"_measurement\"] == \"<INFLUX_BUCKET>\")\n      |\u003e
        filter(fn: (r) =\u003e r[\"_field\"] == \"inverter_power\" or r[\"_field\"]
        == \"house_power\" or r[\"_field\"] == \"grid_power_plus\" or r[\"_field\"]
        == \"grid_power_minus\" or r[\"_field\"] == \"bat_fuel_charge\" or r[\"_field\"]
        == \"bat_power_minus\" or r[\"_field\"] == \"bat_power_plus\")\n      |\u003e
        aggregateWindow(every: 1h, fn: mean)\n      |\u003e sum()\n","dialect":{"header":true,"delimiter":",","annotations":["datatype","group","default"],"commentPrefix":"#","dateTimeFormat":"RFC3339"}}'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - influxdb-client-ruby/1.10.0
      Authorization:
      - Token <INFLUX_TOKEN>
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - text/csv; charset=utf-8
      Date:
      - Sat, 02 Jan 2021 09:00:49 GMT
      Vary:
      - Accept-Encoding
      Content-Length:
      - '905'
    body:
      encoding: UTF-8
      string: "#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,string,string,double\r\n#group,false,false,true,true,true,true,false\r\n#default,_result,,,,,,\r\n,result,table,_start,_stop,_field,_measurement,_value\r\n,,0,2020-12-26T09:00:49.945610001Z,2021-01-02T09:00:49.945610001Z,bat_fuel_charge,<INFLUX_BUCKET>,0\r\n,,1,2020-12-26T09:00:49.945610001Z,2021-01-02T09:00:49.945610001Z,bat_power_minus,<INFLUX_BUCKET>,28.729021662626103\r\n,,2,2020-12-26T09:00:49.945610001Z,2021-01-02T09:00:49.945610001Z,bat_power_plus,<INFLUX_BUCKET>,0\r\n,,3,2020-12-26T09:00:49.945610001Z,2021-01-02T09:00:49.945610001Z,grid_power_minus,<INFLUX_BUCKET>,0\r\n,,4,2020-12-26T09:00:49.945610001Z,2021-01-02T09:00:49.945610001Z,grid_power_plus,<INFLUX_BUCKET>,1409.7025284993995\r\n,,5,2020-12-26T09:00:49.945610001Z,2021-01-02T09:00:49.945610001Z,house_power,<INFLUX_BUCKET>,1776.4633175387564\r\n,,6,2020-12-26T09:00:49.945610001Z,2021-01-02T09:00:49.945610001Z,inverter_power,<INFLUX_BUCKET>,339.41444175922766\r\n\r\n"
  recorded_at: Sat, 02 Jan 2021 09:00:49 GMT
- request:
    method: post
    uri: https://<INFLUX_HOST>/api/v2/query?org=<INFLUX_ORG>
    body:
      encoding: UTF-8
      string: '{"query":"      from(bucket: \"<INFLUX_BUCKET>\")\n      |\u003e range(start:
        -30d)\n      |\u003e filter(fn: (r) =\u003e r[\"_measurement\"] == \"<INFLUX_BUCKET>\")\n      |\u003e
        filter(fn: (r) =\u003e r[\"_field\"] == \"inverter_power\" or r[\"_field\"]
        == \"house_power\" or r[\"_field\"] == \"grid_power_plus\" or r[\"_field\"]
        == \"grid_power_minus\" or r[\"_field\"] == \"bat_fuel_charge\" or r[\"_field\"]
        == \"bat_power_minus\" or r[\"_field\"] == \"bat_power_plus\")\n      |\u003e
        aggregateWindow(every: 1h, fn: mean)\n      |\u003e sum()\n","dialect":{"header":true,"delimiter":",","annotations":["datatype","group","default"],"commentPrefix":"#","dateTimeFormat":"RFC3339"}}'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - influxdb-client-ruby/1.10.0
      Authorization:
      - Token <INFLUX_TOKEN>
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - text/csv; charset=utf-8
      Date:
      - Sat, 02 Jan 2021 09:00:50 GMT
      Vary:
      - Accept-Encoding
      Content-Length:
      - '891'
    body:
      encoding: UTF-8
      string: "#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,string,string,double\r\n#group,false,false,true,true,true,true,false\r\n#default,_result,,,,,,\r\n,result,table,_start,_stop,_field,_measurement,_value\r\n,,0,2020-12-03T09:00:50.07230508Z,2021-01-02T09:00:50.07230508Z,bat_fuel_charge,<INFLUX_BUCKET>,0\r\n,,1,2020-12-03T09:00:50.07230508Z,2021-01-02T09:00:50.07230508Z,bat_power_minus,<INFLUX_BUCKET>,28.729021662626103\r\n,,2,2020-12-03T09:00:50.07230508Z,2021-01-02T09:00:50.07230508Z,bat_power_plus,<INFLUX_BUCKET>,0\r\n,,3,2020-12-03T09:00:50.07230508Z,2021-01-02T09:00:50.07230508Z,grid_power_minus,<INFLUX_BUCKET>,0\r\n,,4,2020-12-03T09:00:50.07230508Z,2021-01-02T09:00:50.07230508Z,grid_power_plus,<INFLUX_BUCKET>,1409.7025284993995\r\n,,5,2020-12-03T09:00:50.07230508Z,2021-01-02T09:00:50.07230508Z,house_power,<INFLUX_BUCKET>,1776.4633175387564\r\n,,6,2020-12-03T09:00:50.07230508Z,2021-01-02T09:00:50.07230508Z,inverter_power,<INFLUX_BUCKET>,339.41444175922766\r\n\r\n"
  recorded_at: Sat, 02 Jan 2021 09:00:50 GMT
recorded_with: VCR 6.0.0
