name: Dedupe Yarn Dependencies

on:
  pull_request_target:
    types: [opened, synchronize]
    branches: [develop]
    paths:
      - 'yarn.lock'

permissions:
  contents: write
  pull-requests: write

jobs:
  dedupe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'yarn'

      - name: Install dependencies (immutable)
        run: yarn install --immutable

      - name: Dedupe
        run: yarn dedupe

      - name: Commit and push if yarn.lock changed
        run: |
          git config user.name "ledermann-bot"
          git config user.email "ledermann-bot@users.noreply.github.com"

          if ! git diff --quiet; then
            git add yarn.lock
            git commit -m 'chore: yarn dedupe'
            git push origin HEAD:${{ github.head_ref }}
          fi
